[package]
name = "create_wikipedia_article_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prog_rs = "0.2.0"
bzip2 = "0.4.3"
parse_mediawiki_dump = "0.1.0"